---
# BRING STACK DOWN
- hosts: loadbalancer
  become: true
  tasks: 
    - name: stopping nginx
      service: name=nginx state=stopped


- hosts: webserver
  become: true
  tasks:
    - name: stopping apache2
      service: name=apache2 state=stopped


# RESTART MYSQL
- hosts: database
  become: true
  tasks:
    - name: resart mysql
      service: name=mysql state=restarted

# BRING STACK UP
- hosts: webserver
  become: true
  tasks: 
    - name: start apache2
      service: name=apache2 state=started

- hosts: loadbalancer
  become: true
  tasks:
    - name: start nginx
      service: name=nginx state=started

